### ISSUE TITLE
Add offsets to NORI_format.md and an Example .nri/.bac file.

### ISSUE THREAD

**Issue by onidenki** [TricksterOnline/TNT#3]
It would be a huge help if we could have Offsets added to the NORI_format.md with an Example .nri/ .bac file to work from when recreating the files in a hex editor.

**Comment by PyroSamurai** [comment]
What offsets are you talking about? I've included all the offsets.

I can't include a .nri/.bac file. It would be considered distribution and therefore illegal. Plus most people already have the client files they want to use it on.

**Comment by onidenki** [comment]
I was thinking of something like this layout:
+-------------------------------------------------------------------------------------------------+
|-NORI-Header-----------------------------------------------------------------------------------|
+--------------------+-----+---------------------------------------------------------------------+
|-Name--------------|Bytes|-----Offset-----|-Description----------------------------------------|
+--------------------+-----+---------------------------------------------------------------------+
|-NORI-Data---------|-40--|---0000-0039--|-NRI-file-structure---10-parameters--------------|
+--------------------+-----+---------------------------------------------------------------------+
|-signature-----------|--4--|---0000-0003---|-NORI-file-signature------------------------------|
+--------------------+-----+----------------------------------------------------------------------+
|-version/type--------|--4--|---0004-0007---|-NORI-format-version-(300,-301,-302,-303)-----|
+--------------------+-----+----------------------------------------------------------------------+
|-param01-05--------|-20--|---0008-0027---|-Unidentified-data--------------------------------|
+--------------------+-----+----------------------------------------------------------------------+
|-anims---------------|--4--|---0028-0031---|-Number-of-included-animations----------------|
+--------------------+-----+----------------------------------------------------------------------+
|-param07------------|--4--|---0032-0035---|-fsize---GAWI-Section-size-----------------------|
+--------------------+-----+----------------------------------------------------------------------+
|-fsize-----------------|--4--|---0036-0039---|-NORI-file-size------------------------------------|
+--------------------+-----+----------------------------------------------------------------------+

also about the example .nri/.bac there are parts of the file that are different from file to file so that is why i said to use an example you can just say use Example: Taiwan's map_sq00_event01.bac and Taiwan's pet489.nri and use the offsets for those files. you don't have to add the code to the project, you can say that they are the example files used in creating the offsets.

**Comment by PyroSamurai** [comment]
No. I made the specification the way it is because I didn't want an example file to be needed.
Plus the offsets would only work up to the end of GAWI_Data (i.e. gsize) without specifying a example file.
Keep in mind this is a format specification and not a guide. It has to be correct 100% of the time.

**Comment by onidenki** [comment]
ok, closing the issue, thank you for clarifying 👍
