### ISSUE TITLE
Can't extract nri

### ISSUE THREAD

**Issue by zaelirving** [TricksterOnline/TNT#6]
Hi! I was trying to extract some Item NRI since I'm trying to fill up TO's wiki fandom page and it seems all the itm_cm_illu_privatia and itm_cm_icon_privatia  NRI's don't extract at all. 

This is the error I get with E

Error in (AM):
java.nio.BufferUnderflowException
Extracting Bitmaps...
Error in (EM):
java.lang.NegativeArraySizeException: -1773177600

and with e

Error in (AM):
java.nio.BufferUnderflowException
Error in (mkCfg):
java.lang.NullPointerException: Cannot load from int array because "NORI.animOffsets" is null
Error in (OptA):
java.lang.NullPointerException

**Comment by PyroSamurai** [comment]
Provide a link to these files. I do not believe they are official client files, so I don't have them.

**Comment by zaelirving** [comment]
If it's specifically from a private server, I guess it's fine, since I'm trying to extract the original items of the game for wiki purposes. Sorry about that.
